### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by noxidsoft** [dchan3/enigma-cms#38]
```
$ npm start

> enigma-cms@ start C:\Documents and Settings\Redacted\Documents\mern\enigma-cms
> nodemon server.bundle.js

[nodemon] 2.0.4
[nodemon] reading config .\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 16580 to restart
[nodemon] ignoring: .\test/**/* .\public/**/* documents/**/*.enigma profiles/**/* site-files/**/*
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.bundle.js`
[nodemon] forking
[nodemon] child pid: 15036
[nodemon] watching 133 files
C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1
const 單="__esModule",序="function",無="undefined",物="object",孩="children",段="p",分="div",指="@@iterator",入="input",數="number",價="value",絲="string",部="component",造="createElement",狀="useState",果="useEffect",情="useContext",同="SamePageAnchor",照="img",伸="span",布="boolean",壹="h1",重="reset",勾="checked",盒="checkbox",處="href",前="useFrontContext",路="useRouterContext",格="td",填="textarea",種="type",連="a",符="symbol",則="defaultValue",效="result",收="radio",選="select",擇="option",帽="Fedora",街="pathname",歷="history",點="location",類="className",設="defaultProps",定="default",復="docTypeNamePlural",始="start",作="createContext",動="action",推="PUSH",泡="POP",名="name",挑="options",庫="dataObj",長="length",油="render",塊="Fragment",解="defineProperty",己="getOwnPropertyDescriptor",代="getOwnPropertySymbols";!function(e){var t={};function r(n){if(t[n])return t[n].exports;var

ReferenceError: regeneratorRuntime is not defined
    at C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:20256
    at Object.<anonymous> (C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:20990)
    at r (C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:885)
    at Object.<anonymous> (C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:12004)
    at r (C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:885)
    at Object.<anonymous> (C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:28618)
    at r (C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:885)
    at Object.<anonymous> (C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:2685)
    at r (C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:885)
    at Object.<anonymous> (C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:66482)
    at r (C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:885)
    at C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:1678
    at Object.<anonymous> (C:\Users\Redacted\Documents\mern\enigma-cms\server.bundle.js:1:1688)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
[nodemon] app crashed - waiting for file changes before starting...
```

Is there quick fix you can identify there?

**Comment by dchan3** [comment]
Try `npm update`, then rebuild and restart.

**Comment by noxidsoft** [comment]
Thanks for the fast reply, still no joy, I'll check my stack.
